#!/usr/bin/env bash
# deploy-site.sh — render, package and publish the Locus landing page.
#
# Usage:
#   VPS=root@host server/scripts/deploy-site.sh
#
# WHY A SCRIPT, AND WHY IT RUNS HERE RATHER THAN ON THE HUB
#
# The page has four download buttons, and every one of them must point at a file
# the current release actually contains. That makes the button URLs a DERIVED
# fact: they are a function of the version being served. Writing them into
# index.html by hand is the mistake docs/operate/CLAIMS.md exists to prevent —
# the page would keep offering 3.2.25 after 3.2.26 shipped, every button would
# 404, and nothing would fail, because a stale URL is indistinguishable from a
# correct one until a human clicks it.
#
# So the URLs are rendered from release-artifacts/manifest.json, which is the
# same file the hub's fetch-release.py resolves asset names against. One source.
# The alternative — rendering on the hub — was rejected deliberately: the hub
# should not be the thing that decides what a public download button points at,
# and it does not carry release-artifacts/ anyway.
#
# WHY THE BUTTONS POINT AT THE HUB AND NOT AT GITHUB
#
# GitHub will only serve a release asset from /releases/download/<tag>/<file> or
# /releases/latest/download/<file> — both are URLs on the repository, so a link
# to an artifact is a link that lands the visitor on the repo's download page.
# The hub already serves the identical files at /updates/<version>/<file> (that
# path exists for the in-app updater), so the page links there instead. The
# visitor gets the file directly; the repo is not involved.
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
SITE_DIR="${REPO_ROOT}/server/site"

# ── Where the download URLs come from ──
#
# The manifest on the LATEST GitHub Release, not release-artifacts/manifest.json.
# That local directory is gitignored scratch left behind by a previous
# publish-release.sh run, and on this workstation it was three versions stale
# (3.2.25 while the live release was 3.2.28) — rendering four buttons pointing at
# files the hub does not have. A stale scratch file is not a source of truth.
#
# The Release manifest is the right source because it is generated by CI from the
# same build it publishes, and its `platforms` map is the SAME mapping the hub's
# publish-release.sh PLATFORMS list uses (and fetch-release.py resolves against,
# and check-consistency.sh section 24 pins). One map, three consumers.
#
# `releases/latest/download/<file>` serves the FILE — it does not redirect to the
# repository — so fetching from it is a plain download, not a page scrape.
#
# Override MANIFEST=/path for an offline or pinned render; CI does this to render
# a page for a version that is not the latest.
MANIFEST_URL="${MANIFEST_URL:-https://github.com/vasilliourous/Locus/releases/latest/download/manifest.json}"

# The hub that serves /updates/. This is the API base from docs/state.toml
# [hub.api_base], and it is deliberately NOT configurable to the landing host:
# the landing block has no /updates/ handle (see modules/05-caddy.sh), so a URL
# under the landing hostname would 404.
HUB_BASE="${HUB_BASE:-https://networkingguides.duckdns.org}"

# The hostname the page is served from. Used for the canonical link and the
# sitemap, and must agree with LANDING_DOMAIN in modules/05-caddy.sh —
# check-consistency.sh asserts that agreement rather than trusting it.
LANDING_DOMAIN="${LANDING_DOMAIN:-locusvpn.jadedns.uk}"

REMOTE_BUNDLE="/root/server/site-dist.tar.gz"

log()  { printf '\033[0;32m[site]\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[site][WARN]\033[0m %s\n' "$*"; }
fail() { printf '\033[0;31m[site][FAIL]\033[0m %s\n' "$*" >&2; exit 1; }

# ── Target must be explicit, for the reason deploy-console.sh documents ──
: "${VPS:?VPS is required, e.g. VPS=root@hub.example.com $0}"

[ -d "$SITE_DIR" ] || fail "site directory not found: $SITE_DIR"
[ -f "$SITE_DIR/index.html" ] || fail "no index.html in ${SITE_DIR}"

log "Target VPS:   ${VPS}"
log "Landing host: ${LANDING_DOMAIN}"
log "Hub base:     ${HUB_BASE}"

# ── Obtain the manifest ──
# Fetched into its OWN temp directory, deliberately NOT the bundle staging dir.
# Writing it there would (a) put a stray manifest.json inside the published page,
# since the staging dir is what gets tarred, and (b) mask the failure, because
# deploy_site() on the hub only asserts named files are PRESENT. That is exactly
# what happened on this script's first run: the bundle failed its own
# index.html-at-root check because the manifest had been fetched into the tree.
WORK="$(mktemp -d -t locus-site-XXXXXX)"
STAGE="${WORK}/bundle"
mkdir -p "$STAGE"
trap 'rm -rf "$WORK"' EXIT

if [ -n "${MANIFEST:-}" ]; then
    [ -f "$MANIFEST" ] || fail "MANIFEST=${MANIFEST} does not exist"
    log "Manifest:     ${MANIFEST} (local override)"
else
    MANIFEST="${WORK}/manifest.json"
    log "Manifest:     ${MANIFEST_URL}"
    curl -fsSL --max-time 60 "$MANIFEST_URL" -o "$MANIFEST" || fail "could not download the release manifest from
     ${MANIFEST_URL}
     Without it the download URLs cannot be rendered, and guessing them is
     exactly the failure this script exists to prevent. Check network access to
     github.com, or pass MANIFEST=/path/to/manifest.json to render offline."
fi

# ── Render ──
# Rendered into a temp tree so a failure halfway through cannot leave a
# partially rewritten server/site/index.html in the working copy. The source
# file stays the template it is documented to be.
cp -a "$SITE_DIR"/. "$STAGE"/

python3 - "$STAGE" "$MANIFEST" "$HUB_BASE" "$LANDING_DOMAIN" <<'PY'
import json, re, sys, pathlib

stage, manifest_path, hub_base, landing = sys.argv[1:5]
index = pathlib.Path(stage) / "index.html"

data = json.loads(pathlib.Path(manifest_path).read_text())
version = data.get("version", "")
platforms = data.get("platforms", {})

if not version:
    raise SystemExit("manifest has no version field")
if not platforms:
    raise SystemExit("manifest has no platforms block")

# The four slots the page carries, in the order they appear. Each maps to a
# FROZEN platform key — the same vocabulary the hub, the client and
# manifest.json use (check-consistency.sh section 1). Do not rename these; the
# page and the manifest must speak the same four words.
SLOTS = ["windows", "linux", "macos_arm", "macos_intel"]

missing = [k for k in SLOTS if k not in platforms]
if missing:
    raise SystemExit(
        "manifest is missing platform entr%s: %s. The page would render a dead "
        "button for each. Present: %s"
        % ("y" if len(missing) == 1 else "ies", ", ".join(missing),
           ", ".join(sorted(platforms)))
    )

html = index.read_text()

# Every slot must exist in the template. A slot that vanished from index.html is
# a silent way to ship three buttons instead of four.
for key in SLOTS:
    if 'data-download="%s"' % key not in html:
        raise SystemExit(
            'index.html has no slot for data-download="%s". Expected all of: %s'
            % (key, ", ".join(SLOTS))
        )

for key in SLOTS:
    filename = platforms[key]["file"]
    url = "%s/updates/%s/%s" % (hub_base.rstrip("/"), version, filename)

    # Replace the href of THIS slot only. Anchored on the attribute so the
    # substitution cannot touch a different slot's href, and `count=1` so a
    # duplicated slot fails loudly rather than being half-rewritten.
    pattern = re.compile(
        r'(data-download="%s"\s+href=")[^"]*(")' % re.escape(key)
    )
    html, n = pattern.subn(lambda m: m.group(1) + url + m.group(2), html, count=1)
    if n != 1:
        raise SystemExit(
            'could not render the href for slot "%s" — expected exactly one '
            'occurrence of data-download="%s" followed by href="…" on the same '
            'tag. Found %d.' % (key, key, n)
        )
    print("    %-12s -> %s" % (key, url))

# The canonical link and the sitemap both name the landing host. Rendered rather
# than hardcoded so that changing LANDING_DOMAIN changes every mention at once,
# and check-consistency.sh still asserts the result matches the Caddyfile.
for path in ("index.html", "sitemap.xml"):
    p = pathlib.Path(stage) / path
    if not p.exists():
        continue
    text = p.read_text()
    text = re.sub(
        r"https://[A-Za-z0-9.\-]+/(?=[\"<])",
        "https://%s/" % landing,
        text,
    )
    p.write_text(text)

# robots.txt carries an absolute Sitemap: URL, which the same regex would miss
# (it is followed by a newline, not a quote).
rb = pathlib.Path(stage) / "robots.txt"
if rb.exists():
    rb.write_text(
        re.sub(r"Sitemap: https://\S+", "Sitemap: https://%s/sitemap.xml" % landing,
               rb.read_text())
    )

index.write_text(html)
PY

log "✓ Rendered download URLs for the manifest's version (see the list above)"

# ── Verify the RENDERED artifact, not the source ──
# These are the same properties deploy_site() re-checks on the hub, asserted here
# too so a rendering failure is caught before it is uploaded rather than after.
for key in windows linux macos_arm macos_intel; do
    grep -q "data-download=\"${key}\" href=\"${HUB_BASE}/updates/" "$STAGE/index.html" \
        || fail "slot '${key}' did not render to a ${HUB_BASE}/updates/ URL.
     The page would ship with a dead button. See the renderer output above."
done

if grep -q 'href="#"' "$STAGE/index.html"; then
    fail "a download slot still points at '#' after rendering"
fi

if ! grep -q "${LANDING_DOMAIN}" "$STAGE/index.html"; then
    fail "index.html carries no reference to ${LANDING_DOMAIN} (canonical link)"
fi

# ── Package ──
# `-C "$STAGE" .` packs the CONTENTS, so index.html sits at the archive root.
# deploy_site() extracts into /var/www/site and requires that level; packing
# "$STAGE" itself would yield ./site/index.html and fail there. Asserted before
# the upload for the same reason deploy-console.sh asserts it: the mistake
# cannot leave this machine.
TARBALL="$(mktemp -t locus-site-tar-XXXXXX.tar.gz)"
# Chained onto the same cleanup as WORK, not a replacement for it: a second
# `trap ... EXIT` REPLACES the first, so this must clean up both or the bundle
# directory leaks on every run.
trap 'rm -f "$TARBALL"; rm -rf "$WORK"' EXIT
tar czf "$TARBALL" -C "$STAGE" .
tar tzf "$TARBALL" | grep -qx './index.html' \
    || fail "packed bundle has no ./index.html at its root — wrong directory level.
     Expected: tar czf BUNDLE -C STAGE .   (NOT: tar czf BUNDLE STAGE)"
log "✓ Packaged ($(du -sh "$STAGE" | cut -f1), index.html at root)"

# ── Upload ──
# Uploaded to /root/server/ so a later setup.sh re-run picks up the same bundle
# rather than reverting to whatever was there before — the same staging contract
# the console bundle has.
log "Uploading to ${VPS}"
scp -q "$TARBALL" "${VPS}:${REMOTE_BUNDLE}" || fail "upload failed"

ssh "$VPS" "
    set -e
    rm -rf /var/www/site/* 2>/dev/null || true
    mkdir -p /var/www/site
    tar xzf '${REMOTE_BUNDLE}' -C /var/www/site
    chown -R root:root /var/www/site
    chmod -R a+rX /var/www/site
    systemctl reload caddy 2>/dev/null || systemctl restart caddy
" || fail "remote deploy failed"
log "✓ Deployed to /var/www/site"

# ── Verify ──
# A warning, not a failure, on a host whose certificate is not issued yet — the
# same nuance deploy-console.sh documents. The bundle is on disk either way.
sleep 2
CODE=$(curl -s -o /dev/null -w '%{http_code}' --max-time 15 "https://${LANDING_DOMAIN}/" || echo 000)
if [ "$CODE" != "200" ]; then
    warn "https://${LANDING_DOMAIN}/ returned HTTP ${CODE}."
    warn "This is EXPECTED on a fresh host where Caddy has no certificate yet —"
    warn "the bundle is uploaded and will be served once Caddy has one."
    warn "If this host is ALREADY running the hub, a non-200 here is a real fault:"
    warn "check that DNS for ${LANDING_DOMAIN} points here and that Cloudflare's"
    warn "SSL/TLS mode is Full (strict) rather than Flexible."
    log "✓ Bundle staged. Continuing without the live-serving check."
    exit 0
fi

BODY=$(curl -s --max-time 15 "https://${LANDING_DOMAIN}/" || true)
for key in windows linux macos_arm macos_intel; do
    echo "$BODY" | grep -q "data-download=\"${key}\" href=\"${HUB_BASE}/updates/" \
        || fail "the SERVED page has no working '${key}' download link"
done
echo "$BODY" | grep -q "${LANDING_DOMAIN}" \
    || warn "the served page does not mention ${LANDING_DOMAIN} — check the canonical link"
log "✓ Serving at https://${LANDING_DOMAIN}/ with 4 wired download links"

# The download surface must not be reachable here. Asserted, not assumed: this is
# the property a future "just add a handle" edit would remove with no visible
# symptom on the page itself.
UP=$(curl -s -o /dev/null -w '%{http_code}' --max-time 10 "https://${LANDING_DOMAIN}/updates/" || echo 000)
if [ "$UP" = "404" ]; then
    log "✓ /updates/ is not exposed on the landing host (404, as intended)"
else
    warn "https://${LANDING_DOMAIN}/updates/ returned ${UP} — expected 404."
    warn "The landing block must not serve the hub's build tree."
fi

log "Done. Open https://${LANDING_DOMAIN}/"
